server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.4.49.238:4000/cloud_user?useSSL=false
    username: root
    password: cloud
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
#      discovery:
#        cluster-name:  HZ # 集群名称

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka: # eureka地址
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

pattern:
  name: local