server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.4.49.238:4000/cloud_order?useSSL=false
    username: root
    password: cloud
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-service # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:  # 服务发现
        ephemeral: false # 非临时实例

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka: # eureka地址
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

user-service: # 配置IRule实现类, 用于调整负载均衡策略为优先选择本地集群 + 随机访问
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule


ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - user-service
feign:
  httpclient:
    enabled: true # 启用Apache httpClient
    max-connections: 200  # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
