server:
  port: 10086 # 服务端口

spring:
  application:
    name: eureka-service # 服务名称

eureka: # eureka微服务也需要注册到注册中心, 为了搭建eureka集群
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
